name: terminal-solitaire
adopt-info: terminal-solitaire
title: Terminal Solitaire
summary: A terminal-based Klondike Solitaire game.
description: |
  A feature-rich, terminal-based implementation of the classic Klondike Solitaire game.
  Features include mouse support, double-click auto-move, and storing high scores.

icon: icon.png
base: core24
grade: stable
confinement: strict
contact: https://github.com/kenvandine/terminal-solitaire/issues
issues: https://github.com/kenvandine/terminal-solitaire/issues
website: https://github.com/kenvandine/terminal-solitaire
source-code: https://github.com/kenvandine/terminal-solitaire
license: GPL-3.0

apps:
  terminal-solitaire:
    command: bin/terminal-solitaire

parts:
  terminal-solitaire:
    plugin: python
    source: .
    python-packages:
      - setuptools
    build-packages:
      - git
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10 || git rev-parse --short HEAD)
